name: NPM Publish package

on:
  workflow_dispatch:
  pull_request:
    types: [ closed ]
    branches: [ 'main' ]
    
defaults:
  run:
    working-directory: Assets/Scripts
env:
  SERVER: ${{ secrets.NPM_REGISTRY_IP }}
  TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
jobs:

  publish:
    if: github.event_name == 'workflow_dispatch' || startsWith(github.head_ref, 'release-please')
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Copy Samples
        run: |
          rm -r -f Assets/Scripts/Samples~/*
          rsync -av --exclude '*.meta' Assets/Samples/* Assets/Scripts/Samples~/
      - name: ㊙️ Creating NPMRC
        run: |
             cat << EOF > .npmrc
             //$SERVER/:_authToken="$TOKEN"
             EOF
      - name: ⬆️ NPM PUBLISH
        run: npm publish --registry http://$SERVER
      - name: ✅ COMPLETE
        run: echo "DONE"
